function private:builddate{                                                                                                                                                                             
   $date = Get-Date -UFormat "%A, %B %e, %Y %t %r"                                                                                                                                                      
   $csclass = 'static class BuildDate { readonly static public string sBuildDate = "'                                                                                                                   
   $csclass = $csclass + $date                                                                                                                                                                          
   $csclass = $csclass + '"; }                                                                                                                                                                          
   // This file is generated by the building script. '                                                                                                                                                  
   #Write-Output $csclass > "KthuraLauncher/builddate.cs"                                                                                                                                               
   $cpp = '#pragma once                                                                                                                                                                                 
   #define BuildDate "' + $date + '"                                                                                                                                                        
   // This file is generated by the building script. ' # I chose a macro, rather than any other approach as a macro will never cause any serious conflict when multiple files/object call this.         
   #Write-Output $csclass | out-file -encoding ASCII "KthuraLauncher/builddate.cs"                                                                                                                       
   Write-Output $cpp | out-file -encoding ASCII "bdate.hpp"                                                                                                                      
   write-host "Build date: " -nonewline -foregroundcolor yellow                                                                                                                                         
   write-host $date -foregroundcolor cyan                                                                                                                                                               
}                                                                                                                                                                                                       

builddate
